src/WebApp/Controllers/APIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using System.IO;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SalesApp.Controllers
{
    [Authorize(Roles = "Order_management")]
    public class APIController : Controller
    {
        private TokenHelper _tokenHelper;

        public APIController(TokenHelper tokenHelper)
        {
            _tokenHelper = tokenHelper;
        }

        // GET: /<controller>/
        public async Task<ActionResult> PlaceOrder()
        {
            var url = GetOrderUrl() + "/api/order/placeorder";
            var token = await _tokenHelper.RetrieveToken(Startup.OrderServiceResourceId);

            return await ExecuteCall(url, token);
        }

        public async Task<ActionResult> PlaceOrderV2()
        {
            var url = GetOrderUrl() + "/api/order/placeorderv2";
            var token = await _tokenHelper.RetrieveToken(Startup.OrderServiceResourceId);

            return await ExecuteCall(url, token);
        }

        public async Task<ActionResult> ReadInventory()
        {
            var url = GetInventoryUrl() + "/api/inventory/read";
            var token = await _tokenHelper.RetrieveToken(Startup.InventoryServiceResourceId);

            return await ExecuteCall(url, token);
        }

        public async Task<ActionResult> WriteInventory()
        {
            var url = GetInventoryUrl() + "/api/inventory/write";
            var token = await _tokenHelper.RetrieveToken(Startup.InventoryServiceResourceId);

            return await ExecuteCall(url, token);
        }

        private async Task<ActionResult> ExecuteCall(string url, string token)
        {
            HttpClient client = new HttpClient();
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, url);
            
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

            HttpResponseMessage response = await client.SendAsync(request);

            if (response.IsSuccessStatusCode)
            {
                var responseToken = await response.Content.ReadAsStringAsync();
                ViewBag.StatusCode = response.StatusCode;
                ViewBag.Token = _tokenHelper.TokenPrettify(responseToken);
                return View("Claims");
            }
            else if (response.StatusCode == System.Net.HttpStatusCode.Forbidden)
            {
                var responseToken = await response.Content.ReadAsStringAsync();
                ViewBag.StatusCode = response.StatusCode;
                ViewBag.Token = _tokenHelper.TokenPrettify(responseToken);
                return View("Claims");
            }
            else
            {
                return View("Error");
            }
        }

        private string GetInventoryUrl()
        {
            return "https://localhost:44321";
        }

        private string GetOrderUrl()
        {
            return "https://localhost:44346";
        }
    }
}

src/WebApp/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Http.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace SalesApp.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult SignIn()
        {
            return Challenge(
                new AuthenticationProperties { RedirectUri = "/" }, OpenIdConnectDefaults.AuthenticationScheme);
        }

        public IActionResult SignOut()
        {
            var callbackUrl = Url.Action("SignedOut", "Account", values: null, protocol: Request.Scheme);
            return SignOut(new AuthenticationProperties { RedirectUri = callbackUrl },
                CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectDefaults.AuthenticationScheme);
        }

        public IActionResult SignedOut()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                // Redirect to home page if the user is authenticated.
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            return View();
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

src/WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using System.Net.Http;
using System.Net.Http.Headers;
using Microsoft.Azure.ActiveDirectory.GraphClient;
using Microsoft.Azure.ActiveDirectory.GraphClient.Extensions;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Http.Authentication;

namespace SalesApp.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private TokenHelper _tokenHelper;

        public HomeController(TokenHelper tokenHelper)
        {
            _tokenHelper = tokenHelper;
        }

        public IActionResult Index()
        {
            ViewBag.Token = _tokenHelper.TokenPrettify(User.Claims.First(claim => claim.Type == "idtoken").Value);
            return View();
        }

        [Authorize(Roles = "Reporting")]
        public async Task<ActionResult> ListEmployees()
        {
            // Get the AD Graph client
            var client = GetActiveDirectoryClient();

            // Retrieve persons reporting to me
            var users = new List<User>();
            var result = await client.Me.DirectReports.ExecuteAsync();

            await Merge(users, result);
            ViewBag.Employees = string.Join(
                Environment.NewLine, users.Select(user => user.DisplayName).ToArray());
            return View("Employees");

            // Just for fun: this is how you'd query the Graph API for groups the user is a member of
            // var result = await client.Me.MemberOf.ExecuteAsync();
        }

        public IActionResult Error()
        {
            return View();
        }

        private ActiveDirectoryClient GetActiveDirectoryClient()
        {
            // Setup the URI to the Graph API
            Uri baseServiceUri = new Uri(Startup.GraphResourceId);

            // Create client using the base URI, our tenant ID and the token delegate
            ActiveDirectoryClient activeDirectoryClient =
                new ActiveDirectoryClient(new Uri(baseServiceUri, Startup.TenantId),
                    async () => await _tokenHelper.RetrieveToken(Startup.GraphResourceId));
            return activeDirectoryClient;
        }

        private async Task Merge<T>(List<T> items, IPagedCollection<IDirectoryObject> items2)
        {
            items.AddRange(items2.CurrentPage.Where(item => item is T).Cast<T>());
            if (items2.MorePagesAvailable)
            {
                var nextPage = await items2.GetNextPageAsync();
                await Merge(items, nextPage);
            }
        }
    }
}

src/WebApp/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Http.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SalesApp.Controllers
{
    public class SessionController : Controller
    {
        // GET: /<controller>/
        public IActionResult Refresh()
        {
            // TODO: Fix; somehow challenge is currently redirecting to Cookie Middleware's Access Denied page...
            return Challenge(OpenIdConnectDefaults.AuthenticationScheme);
            //HttpContext.Authentication.ChallengeAsync(OpenIdConnectDefaults.AuthenticationScheme, new AuthenticationProperties(), Microsoft.AspNetCore.Http.Features.Authentication.ChallengeBehavior.Automatic);
        }
    }
}

src/WebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/WebApp/Views/Home/Employees.cshtml
@{
    ViewData["Title"] = "Employees";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<pre>
@ViewBag.Employees
</pre>

src/WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="bodyheader">
    <p>
        TechDays TV Sales App
    </p>
</div>

<pre class="token">
@ViewBag.Token
</pre>

src/WebApp/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "Access Denied";
}
<h2>@ViewData["Title"]</h2>
<h3>You don't have access to this feature</h3>

src/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sales App</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Sales App</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-nav-center">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="API" asp-action="PlaceOrder">Place Order</a></li>
                    <li><a asp-area="" asp-controller="API" asp-action="PlaceOrderV2">Place Order v2</a></li>
                    <li><a asp-area="" asp-controller="API" asp-action="ReadInventory">Read Inventory</a></li>
                    <li><a asp-area="" asp-controller="API" asp-action="WriteInventory">Write Inventory</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="ListEmployees">List Employees</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Sales App</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>